### PR TITLE
Use make's double-suffix rules to simplify Makefile

### PR DESCRIPTION
**Pull request by reebsd**
This requires moving Makefile into the src/ directory, but it lets use use `.cpp.o:` and opens the ability to use `%.o: %.cpp` in the future, even on FreeBSD and OpenBSD.
Test that it works on your system, please! (btw, this is something CI would automatically test)
As always, read the individual commit messages for more details.

### CODE REVIEW

**Comment by reebsd** [comment]
I realise in one commit description I write we can replace the SRCS line in a separate commit, but in fact, we can **delete** the SRCS line in a separate commit.

**Comment by reebsd** [comment]
Or in this one.  I deleted the `SRCS=` line.

**Comment by RosettaHS** [comment]
Hesitant on approving this. Causes severe slowdowns during compilation (up to 50%).  I could see this being a huge problem further down the line. I think I'll stick with what I have now. 

Another thing I want to mention is there shouldn't be too much of a focus on getting OKit on non-Linux systems due to the lack of the /proc/ filesystem that Orion strictly requires. Running individual non-native OKit applications on non-Linux system might work, but the moment any Orion-Native applications try to run (including the DE) would immediately crash due to the lack of the /proc/ filesystem. The Orion Application Structure requires this.

**Comment by reebsd** [comment]
> Causes severe slowdowns during compilation (up to 50%)

I also noticed the slowdown.  I'll close this, since this was only to show what options we had in regards to simplification.

> I think I'll stick with what I have now.

> Another thing I want to mention is there shouldn't be too much of a focus on getting OKit on non-Linux systems

Thumbs-up.

**Pull request closed without merging**
