### PR TITLE
Make OKit build on FreeBSD and OpenBSD

### PR DESCRIPTION
**Pull request by reebsd**
Hi!  I'm the FreeBSD /g/ poster who commented in your thread, and I made a GitHub account just for this! (I'll likely delete my account in a month)
These patches make OKit build on FreeBSD and OpenBSD.  They also add a -q flag to INSTALL.sh and UNINSTALL.sh that lets users use those scripts without ASCII art if they so request.  I also made most of the y/n questions default to No.
I'm a C and Unix programmer, and I DO NOT know C++, so please check the C++ diffs carefully.
I can set up Travis CI and Cirrus CI if you'd like, to have this repository automatically get built on GNU/Linux and FreeBSD, for free, if you'd like.
Please read the commit description for each of the seven commits.

### CODE REVIEW

**Comment by reebsd** [comment]
I'll note that while OApp compiles, and then runs, it doesn't work 100% right.
On FreeBSD, the output of running OApp, alt-tabbing in and out of it twice, then quitting:
```
$ ./OApp 
OKIT | ERROR! Failed to get binary path!
OKIT | ERROR! FAILED TO CHANGE TO BINARY PATH (null)
OCol 0x20abb0 ( 0 ,0 ,0 )
CXEvent 0x7fffffffe390 | valid true | type 2 | xtype 12 | {
        expose.x 0
        expose.y 0
        expose.w 100
        expose.h 100
}
CXEvent 0x7fffffffe390 | valid true | type 2 | xtype 12 | {
        expose.x 0
        expose.y 0
        expose.w 100
        expose.h 100
}
^C
$ 
```
And verbosely:
```
$ make run
O_VERBOSE=1 ./OApp
OKIT | Initialising Application.
OKIT | Running in verbose mode!
OKIT | Application Name:                My OApp
OKIT | Username:                        (null)
OKIT | Current Directory:               æÿÿÿ
OKIT | Are Errors Fatal?:               false
OKIT | ERROR! Failed to get binary path!
OKIT | ERROR! FAILED TO CHANGE TO BINARY PATH (null)
OKIT | Full Binary path is:             (null)
OKIT | Full Binary directory is:        (null)
OKIT | Data path is:                    /home/dogg/.local/share/My OApp
OKIT | Is Native OApp?                  false
OKIT | Service sucessfully initialised!
OKIT | Successfully created CContext( 0x0 , 0 , 0 , 400 , 350, true )
OCol 0x20abb0 ( 0 ,0 ,0 )
OKIT | Successfully created CContext( 0x7fffffffe538 , 0 , 0 , 100 , 100, true )
CXEvent 0x7fffffffe300 | valid true | type 2 | xtype 12 | {
        expose.x 0
        expose.y 0
        expose.w 100
        expose.h 100
}
CXEvent 0x7fffffffe300 | valid true | type 2 | xtype 12 | {
        expose.x 0
        expose.y 0
        expose.w 100
        expose.h 100
}
^C*** Signal 2

$ 
```
This is likely because FreeBSD doesn't have a real /proc/ filesystem.

**Comment by reebsd** [comment]
Also despite the
```
OKIT | Current Directory:               æÿÿÿ
```
line in the verbose mode, I **did** confirm my version of _initCWD() works and it **does** get the working directory correctly.

**Comment by reebsd** [comment]
That's making me wonder.  If I printf the value of cwd at the end of _initCWD() it works right.  But this unusual æÿÿÿ is from further down in the same .cpp file.

**Comment by reebsd** [comment]
Actually, I know why.  updated diff coming.

**Comment by reebsd** [comment]
Fixed.  Ready to merge.
```
$ make run
O_VERBOSE=1 ./OApp
OKIT | Initialising Application.
OKIT | Running in verbose mode!
OKIT | Application Name:                My OApp
OKIT | Username:                        (null)
OKIT | Current Directory:               /usr/home/dogg/Downloads/OKit-main
OKIT | Are Errors Fatal?:               false
OKIT | ERROR! Failed to get binary path!
OKIT | ERROR! FAILED TO CHANGE TO BINARY PATH (null)
OKIT | Full Binary path is:             (null)
OKIT | Full Binary directory is:        (null)
OKIT | Data path is:                    /home/dogg/.local/share/My OApp
OKIT | Is Native OApp?                  false
OKIT | Service sucessfully initialised!
OKIT | Successfully created CContext( 0x0 , 0 , 0 , 400 , 350, true )
OCol 0x20ab90 ( 0 ,0 ,0 )
OKIT | Successfully created CContext( 0x7fffffffe548 , 0 , 0 , 100 , 100, true )
CXEvent 0x7fffffffe310 | valid true | type 2 | xtype 12 | {
        expose.x 0
        expose.y 0
        expose.w 100
        expose.h 100
}
^C*** Signal 2

$ 
```

**Comment by reebsd** [comment]
If this pull request is accepted, I also have in mind some diffs to fix the other (null) results.  At the very least, I know how to fix the username one: with either getlogin(), getpwuid(geteuid()), or getpwuid(getuid())

**Review by RosettaHS — APPROVED** [review]
This makes it a bit trickier for me since there's a good reason why I used "*.o" for BINS instead of writing them all out, but if this makes it more portable then I'll live with it. All seems good, merging.

**Review by RosettaHS — APPROVED** [review]
Good eye, I should have caught this. I have no idea how it worked at all without "X::". CXEvent is a class within the X namespace, meaning accessing it outside of that namespace would require an "X::" prefix.

As for the double underscores, my justification is that OKit is a core and essential part of the Orion Operating system, but 'll consider swapping out the macros for a more traditional style at some point.

**Comment by RosettaHS** [comment]
I'm going to need to do a lot of modifications still but everything seems to work just fine with this. Merging.

**Comment by reebsd** [comment]
Glad it all works, and glad to help!
Thanks for the C++ explanation, too. (I really should learn C++ some day but that day never happens, haha)

**Comment by RosettaHS** [comment]
Another thing, might I ask why "\*.cpp" was replaced by the individual files? They accomplish the exact same goal but now it's harder since with every CPP file I make I have to add it to the list manually? That's a lot of work given there will be a lot of modules, surely it makes more sense to just have "\*.cpp" instead since it'll scale far easier, and OKit only intends to use XLib only anyway.

**Comment by reebsd** [comment]
@RosettaHS 
There never was a `*.cpp`, there was a `%.o: src/%.cpp`.  And `%.o: src/%.cpp` was breaking the build on FreeBSD.
However, you're right that we can use `*.cpp`.
In the Makefile, feel free to replace
```
SRCS=src/CContainable.cpp src/CContainer.cpp src/CContext.cpp src/CNodeArray.cpp src/CXEvent.cpp src/OCol.cpp src/OContainer.cpp src/OService.cpp src/OString.cpp src/OTheme.cpp src/OVec.cpp src/application.cpp src/xservice.cpp
```
with
```
SRCS=src/*.cpp
```

Semi-related:
However, since BINS and ALLBINS are different lists, you can't use `*.o` for BINS.  You can, however, use it for ALLBINS if you wish to.

**Comment by RosettaHS** [comment]
I'll tweak it and see what I can do. How exactly was it breaking FreeBSD though, if you know by chance?

**Comment by reebsd** [comment]
Rules using % aren't compatible with all versions of `make`.  That, I know for sure.
I think I have some workarounds in mind, I'll send one or two pull requests in a bit.

**Comment by reebsd** [comment]
Made one pull request:
https://github.com/RosettaHS/OKit/pull/3

**Pull request merged**
